[package]
name = "rip8"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/OctavioGalland/rip8"
license = "GPL-3.0-only"

[dependencies]
rand = "0.8.5"
sdl2 = "0.37"
clap = { version = "4.0", features = ["derive"] }
